import { FormField } from "@/types/form";

export const FORM_FIELDS: FormField[] = [
  { category: "Ship Information", name: "ship_name", label: "Ship name", type: "text" },
  { category: "Ship Information", name: "call_sign", label: "Call sign", type: "text" },
  { category: "Ship Information", name: "ship_type", label: "Ship type", type: "radio" },
  { category: "Ship Information", name: "length", label: "Length", type: "number" },
  { category: "Ship Information", name: "beam", label: "Beam", type: "number" },
  { category: "Ship Information", name: "draft", label: "Draft", type: "number" },
  { category: "Ship Information", name: "engine", label: "Engine type", type: "radio" },
  {
    category: "Cam Focal Length",
    name: "cam_fx[0]",
    label: "Left Cam Focal Length X",
    type: "number",
  },
  {
    category: "Cam Focal Length",
    name: "cam_fy[0]",
    label: "Left Cam Focal Length Y",
    type: "number",
  },
  {
    category: "Cam Focal Length",
    name: "cam_fx[1]",
    label: "Center Cam Focal Length X",
    type: "number",
  },
  {
    category: "Cam Focal Length",
    name: "cam_fy[1]",
    label: "Center Cam Focal Length Y",
    type: "number",
  },
  {
    category: "Cam Focal Length",
    name: "cam_fx[2]",
    label: "Right Cam Focal Length X",
    type: "number",
  },
  {
    category: "Cam Focal Length",
    name: "cam_fy[2]",
    label: "Right Cam Focal Length Y",
    type: "number",
  },
  {
    category: "Cam Principal Length",
    name: "cam_px[0]",
    label: "Left Cam Principal Length X",
    type: "number",
  },
  {
    category: "Cam Principal Length",
    name: "cam_py[0]",
    label: "Left Cam Principal Length Y",
    type: "number",
  },
  {
    category: "Cam Principal Length",
    name: "cam_px[1]",
    label: "Center Cam Principal Length X",
    type: "number",
  },
  {
    category: "Cam Principal Length",
    name: "cam_py[1]",
    label: "Center Cam Principal Length Y",
    type: "number",
  },
  {
    category: "Cam Principal Length",
    name: "cam_px[2]",
    label: "Right Cam Principal Length X",
    type: "number",
  },
  {
    category: "Cam Principal Length",
    name: "cam_py[2]",
    label: "Right Cam Principal Length Y",
    type: "number",
  },
  { category: "Roll Pitch Yaw", name: "rpy[0]", label: "Left Roll", type: "number" },
  { category: "Roll Pitch Yaw", name: "rpy[1]", label: "Left Yaw", type: "number" },
  { category: "Roll Pitch Yaw", name: "rpy[2]", label: "Left Pitch", type: "number" },
  { category: "Roll Pitch Yaw", name: "rpy[3]", label: "Center Roll", type: "number" },
  { category: "Roll Pitch Yaw", name: "rpy[4]", label: "Center Yaw", type: "number" },
  { category: "Roll Pitch Yaw", name: "rpy[5]", label: "Center Pitch", type: "number" },
  { category: "Roll Pitch Yaw", name: "rpy[6]", label: "Right Roll", type: "number" },
  { category: "Roll Pitch Yaw", name: "rpy[7]", label: "Right Yaw", type: "number" },
  { category: "Roll Pitch Yaw", name: "rpy[8]", label: "Right Pitch", type: "number" },
];
